---
abstract: 'consciousness substrate'
author:
  - 'Steve Craig <drsteve@cpan.org>'
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
  repository: http://github.com/st3vil/stylehouse
version: 0.03
